import { generateObject } from 'ai';
import { createOpenAI } from '@ai-sdk/openai';
import { z } from 'zod';

const gateway = createOpenAI({
    apiKey: process.env.AI_GATEWAY_API_KEY || '',
    baseURL: 'https://ai-gateway.vercel.sh/v1',
});

// Using a high duration as this can be a complex synthesis task
export const maxDuration = 120;

// Recreating the frontend INIT schema
const itemSchema = z.object({
    id: z.string().describe("Unique sub-item ID, e.g., '1a'"),
    sub: z.string().describe("Name of the sub-service or product, e.g., 'Basic Plan (Rs.299/mo)'"),
    qty: z.number().optional().describe("Quantity per month. Used for P1 Rev, OPEX, CAPEX. Default to 0."),
    qtyDay: z.number().optional().describe("Quantity per day. Used ONLY for P2 Rev. Default to 0."),
    price: z.number().optional().describe("Price per unit for Revenue streams. Default to 0."),
    cost: z.number().optional().describe("Cost per unit for OPEX and CAPEX. Default to 0."),
    gY1: z.number().describe("Growth rate from Y1 to Y2 as a decimal (e.g. 0.10 for 10%)"),
    gY2: z.number().describe("Growth rate from Y2 to Y3 as a decimal"),
    gY3: z.number().describe("Growth rate from Y3 to Y4 as a decimal"),
    gY4: z.number().describe("Growth rate from Y4 to Y5 as a decimal"),
    gY5: z.number().describe("Growth rate from Y5 to Y6 as a decimal"),
});

const groupSchema = z.object({
    id: z.string().describe("Unique major group ID, e.g., '1'"),
    header: z.string().describe("Name of the major category, e.g., 'Health Membership Plans'"),
    items: z.array(itemSchema).describe("List of exactly 5 sub-items under this category."),
});

const formSchema = z.object({
    basics: z.object({
        legalName: z.string().describe("Legal company name"),
        tradeName: z.string().describe("Trade or brand name"),
        address: z.string().describe("Business address or location"),
        email: z.string().describe("Contact email"),
        contact: z.string().describe("Contact phone number"),
        promoters: z.string().describe("Number of promoters or founders"),
        startDateP1: z.string().describe("Format YYYY-MM-DD for Phase 1 start"),
        startDateP2: z.string().describe("Format YYYY-MM-DD for Phase 2 start"),
        description: z.string().describe("Short description of the business model"),
        pitchDeck: z.string().optional().describe("Link to pitch deck if any"),
        burningDesire: z.string().describe("The core mission or vision"),
    }),
    revP1: z.array(groupSchema).describe("Phase 1 Revenue Streams. Usually 5 groups. Must use 'qty' and 'price'."),
    revP2: z.array(groupSchema).describe("Phase 2 Revenue Streams. Usually 5 groups. Must use 'qtyDay' and 'price'."),
    opex: z.array(groupSchema).describe("Operating Expenses. Usually 5 groups. Must use 'qty' and 'cost'."),
    capex: z.array(groupSchema).describe("Capital Expenditures. Usually 2-3 groups. Must use 'qty' and 'cost'."),
    costing: z.array(groupSchema).describe("Cost of Goods Sold (Costing). Usually 5 groups. Must use 'qtyDay' and 'cost'."),
    funding: z.array(z.object({
        id: z.string(),
        header: z.string(),
        amount: z.number(),
        equity: z.number().describe("Equity percentage given up as decimal (e.g. 0.15 for 15%)")
    })).describe("Funding sources list.")
});

const SYSTEM_PROMPT = `
You are FIna, an expert financial modeler and strategic analyst.
The user is providing you with a raw "Strategic Execution Plan" generated by a Business Validator AI.

YOUR MISSION:
Extract all relevant business context, revenue streams, expected pricing, operating costs, and capital expenditures from this plan, and map it STRICTLY into the provided JSON schema. We use this JSON to instantly build their Financial Model dashboard.

CRITICAL INSTRUCTIONS:
1. **P1 vs P2 Revenue**: 'revP1' uses 'qty' (per month). 'revP2' uses 'qtyDay' (per day).
2. **Pricing/Costs**: Revenue uses 'price'. Expenses (OPEX/CAPEX/Costing) use 'cost'.
3. **Empty Rows**: For each group in revP1, revP2, opex, capex, and costing, try to provide exactly 5 items. If there are fewer than 5 real items, fill the remaining with blank items (empty strings for 'sub', and 0 for all numbers).
4. **Growth Rates**: 'gY1' through 'gY5' represent year-over-year decimal growth (0.10 = 10% growth). Estimate realistic scaling based on standard startup metrics unless explicitly stated otherwise in the plan.
5. **IDs**: Group IDs should be simple strings: "1", "2", "3". Sub-item IDs should prefix the group ID: "1a", "1b", "1c".
6. If the plan lacks specific numeric details (like exact prices or exact quantities), use realistic, logical estimates for their industry to build a comprehensive base model they can edit later.
`;

export async function POST(req) {
    try {
        const { strategyPlan } = await req.json();

        if (!strategyPlan) {
            return new Response(JSON.stringify({ error: "Missing strategyPlan text" }), { status: 400 });
        }

        const { object } = await generateObject({
            model: gateway(process.env.AI_GATEWAY_MODEL || 'anthropic/claude-sonnet-4-5'),
            system: SYSTEM_PROMPT,
            schema: formSchema,
            prompt: "Here is the Strategic Execution Plan. Parse and convert it to our strict financial model JSON structure:\n\n" + strategyPlan,
        });

        return new Response(JSON.stringify(object), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });

    } catch (error) {
        console.error("Failed to generate financial model from plan:", error);
        return new Response(JSON.stringify({ error: "Failed to parse. Please try again." }), { status: 500 });
    }
}
